// Constants
export const AVAILABLE_ARTISTS = [
    'Billie Eilish',
    'Post Malone',
    'Benson Boone',
    'The Weeknd', 
    'Sabrina Carpenter',
    'Olivia Rodrigo', 
    'Carly Rae Jepsen',
    'Glass Animals',
    'Gracie Abrams',
    'Tyla',
    'Everglow',
    'SZA',
    'Conan Gray',
    'Raye',
    'Stephen Sanchez',
    'Kissoflife',
    'Thuy',
    'Cannons',
    'Dominic Fike',
    'FLO',
];


export const PERSONAL_RANKING = [
    'Taylor Swift',
    'IU',
    'Zhou Shen',
    'Billie Eilish',
    'Blackpink',
    'JJ Lin',
    'Post Malone',
    'Benson Boone',
    'G.E.M',
    'The Weeknd',
    'Itzy',
    'Sabrina Carpenter',
    'G-idle',
    'Ive',
    'Olivia Rodrigo',
    'Carly Rae Jepsen',
    'Glass Animals',
    'Gracie Abrams',
    'Tyla',
    'Tyler the Creator',
    'Wheein',
    'Everglow',
    'Aespa',
    'Yoasobi',
    'SZA',
    'Conan Gray',
    'Raye',
    'Stephen Sanchez',
    'Kissoflife',
    'Thuy',
    'Cannons',
    'Dominic Fike',
    'FLO',
];